Adding More from JoshSurber
Adding some compression formats from Josh Surber as well as his up
function.

https://surber.us/blog/2025/01/bash-dotfiles/

diff --git a/shell/bash_aliases.d/filesystem b/shell/bash_aliases.d/filesystem
--- a/shell/bash_aliases.d/filesystem
+++ b/shell/bash_aliases.d/filesystem
@@ -37,3 +37,23 @@ alias dig-holes="fallocate --dig-holes"
 if cmds_exist sfs; then
   alias organize_downloads="sfs ~/.config/sfs/Dowloads.yaml ~/Downloads"
 fi
+
+# Move up $ARGS directories (default 1)
+up() {
+  local d=""
+  local limit="$1"
+
+  # Default to limit of 1
+  if [ -z "$limit" ] || [ "$limit" -le 0 ]; then
+    limit=1
+  fi
+
+  for ((i = 1; i <= limit; i++)); do
+    d="../$d"
+  done
+
+  # perform cd. Show error if cd fails
+  if ! cd "$d"; then
+    echo "Couldn't go up $limit dirs."
+  fi
+}
